### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by triniwiz** [triniwiz/nativescript-image-cache-it#1]
User SDWebImage for ios version
- https://github.com/rs/SDWebImage

**Comment by slavaGanzin** [comment]
:+1:

**Comment by manijak** [comment]
@triniwiz @VideoSpike

Please merge the two plugins, we don't need one for each platform :)

https://github.com/VideoSpike/nativescript-web-image-cache

**Comment by triniwiz** [comment]
I love the idea but the markups are off :confused:

**Comment by triniwiz** [comment]
Done
