### ISSUE TITLE
Error on load page 

### ISSUE THREAD

**Issue by MuhammadTahir92** [triniwiz/nativescript-image-cache-it#23]
System.err: Calling js method onCreateViewHolder failed
System.err: TypeError: Cannot read property 'get' of undefined
System.err: File: "file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js, line: 15, column: 68
System.err: StackTrace:
System.err:     Frame: function:'ImageCacheIt.createNativeView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js', line: 15, column: 69
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
System.err:     Frame: function:'ListViewAdapter.onCreateViewHolder', file:'file:///data/data/org.nativescript.tradelivemobile/files/app/tns_modules/nativescript-pro-ui/listview/listview.js', line: 104, column: 26
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.gen.com.telerik.widget.list.ListViewAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.onCreateViewHolder(com.telerik.widget.list.ListViewAdapter.java)
System.err:     at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:459)
System.err:     at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:20)
System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
System.err:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
System.err:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
System.err:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
System.err:     at com.telerik.widget.list.RadListView.onLayout(RadListView.java:587)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:614)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
System.err:     at android.view.View.layout(View.java:16630)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:606)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process org.nativescript.tradelivemobile (pid 4113) has died

My html code

` <ImageCacheIt stretch="aspectFit" centerCrop="false" resize="300,300" imageUri="http://screenrant.com/wp-content/uploads/The-Flash-vs-the-Reverse-Flash.jpg"></ImageCacheIt>
 `

my module is 
`
import { registerElement } from 'nativescript-angular/element-registry';
registerElement(
  'ImageCacheIt',
  () => require('nativescript-image-cache-it').ImageCacheIt
);`

**Comment by triniwiz** [comment]
You might want to try nuking your node modules, platforms and the package-lock.json you might have an old version installed

**Comment by MuhammadTahir92** [comment]
well so what i have to do now ?

**Comment by MuhammadTahir92** [comment]
I install the new version but the error remain same
