### ISSUE TITLE
Nativescript Angular 2 

### ISSUE THREAD

**Issue by MuhammadTahir92** [triniwiz/nativescript-image-cache-it#25]
demo project is not working and the error logs is :

System.err: com.tns.NativeScriptException:
System.err: Calling js method getView failed
System.err: TypeError: Could not load view for: ImageCacheIt.Error: com.tns.NativeScriptException: Failed to find module: "nativescript-image-cache-it", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err:     android.widget.AbsListView.obtainView(AbsListView.java:2474)
System.err:     android.widget.ListView.measureHeightOfChildren(ListView.java:1301)
System.err:     android.widget.ListView.onMeasure(ListView.java:1203)
System.err:     android.view.View.measure(View.java:19175)
System.err:     org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     android.view.View.measure(View.java:19175)
System.err:     org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     android.view.View.measure(View.java:19175)
System.err:     org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     android.view.View.measure(View.java:19175)
System.err:     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6116)
System.err:     android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
System.err:     android.view.View.measure(View.java:19175)
System.err:     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6116)
System.err:     android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
System.err:     android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
System.err:     android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
System.err:     android.view.View.measure(View.java:19175)
System.err:     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6116)
System.err:     android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
System.err:     com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2693)
System.err:     android.view.View.measure(View.java:19175)
System.err:     android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2481)
System.err:     android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1440)
System.err:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1694)
System.err:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
System.err:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
System.err:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
System.err:     android.view.Choreographer.doCallbacks(Choreographer.java:696)
System.err:     android.view.Choreographer.doFrame(Choreographer.java:631)
System.err:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
System.err:     android.os.Handler.handleCallback(Handler.java:815)
System.err:     android.os.Handler.dispatchMessage(Handler.java:104)
System.err:     android.os.Looper.loop(Looper.java:207)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5728)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: File: "file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 15104, column: 8
System.err: StackTrace:
System.err:     Frame: function:'getViewClass', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/element-registry.js', line: 88, column: 15
System.err:     Frame: function:'ViewUtil.createView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/view-util.js', line: 201, column: 44
System.err:     Frame: function:'NativeScriptRenderer.createElement', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/renderer.js', line: 109, column: 30
System.err:     Frame: function:'DebugRenderer2.createElement', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 15203, column: 49
System.err:     Frame: function:'createElement', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 10576, column: 27
System.err:     Frame: function:'createViewNodes', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13741, column: 61
System.err:     Frame: function:'createEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13657, column: 5
System.err:     Frame: function:'callWithDebugContext', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 15094, column: 42
System.err:     Frame: function:'debugCreateEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 14406, column: 12
System.err:     Frame: function:'TemplateRef_.createEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 11732, column: 38
System.err:     Frame: function:'ViewContainerRef_.createEmbeddedView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 11444, column: 52
System.err:     Frame: function:'ListViewComponent.onItemLoading', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/directives/list-view-comp.js', line: 113, column: 35
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 100, column: 32
System.err:     Frame: function:'ListViewAdapter.getView', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 242, column: 24
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2474)
System.err:     at android.widget.ListView.measureHeightOfChildren(ListView.java:1301)
System.err:     at android.widget.ListView.onMeasure(ListView.java:1203)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1055)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:865)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6116)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6116)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6116)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2693)
System.err:     at android.view.View.measure(View.java:19175)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2481)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1440)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1694)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:696)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:631)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
System.err:     at android.os.Handler.handleCallback(Handler.java:815)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
System.err:     at android.os.Looper.loop(Looper.java:207)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5728)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
ActivityManager: Process org.nativescript.demong (pid 30144) has died
ActivityManager: SVC-handleAppDiedLocked: app = ProcessRecord{4992b16 30144:org.nativescript.demong/u0a612}, app.pid = 30144

app.module.ts
`import { registerElement } from "nativescript-angular/element-registry";
registerElement("ImageCacheIt", () => require("nativescript-image-cache-it").ImageCacheIt);`

items.component.ts
`<StackLayout class="page">
    <ListView [items]="items | async" class="list-group">
        <ng-template let-item="item">
            <GridLayout class="list-group-item" columns="auto,*" [nsRouterLink]="['/item', item.id]" [text]="item.name">
                <ImageCacheIt placeHolder="res://place" errorHolder="res://error" [stretch]="stretch" [borderRadius]="borderRadius" [borderWidth]="borderWidth"
                    [borderColor]="borderColor" width="100" height="100" [imageUri]="item.url"></ImageCacheIt>
                <StackLayout col="1">
                    <Label [text]="item.url"></Label>
                </StackLayout>
            </GridLayout>
        </ng-template>
    </ListView>
</StackLayout>`

`xport class ItemsComponent implements OnInit {
  items: BehaviorSubject<Item[]>;
  stretch = 'fill';
  borderRadius = 50;
  borderWidth = 1;
  borderColor = 'red';`

**Comment by vahidvdn** [comment]
This also happens to me in playground. Any idea?
