### ISSUE TITLE
Cannot style images (border)

### ISSUE THREAD

**Issue by manijak** [triniwiz/nativescript-image-cache-it#3]
I tried setting a border-radius via css, but it didn't work. The image is always square. 

```
JS: Style: Error setting property: borderRadius on ImageCacheIt(245)@file:///app/views/players/player.xml:22:30;: 
TypeError: v._nativeView.setCornerRadius is not a function
```

**Comment by triniwiz** [comment]
Fixed with https://github.com/triniwiz/nativescript-image-cache-it/commit/3d3b5578919ff91b19ae6045f09a6974819200f7 please update to 1.3.1
