### ISSUE TITLE
White space around image

### ISSUE THREAD

**Issue by Tyg-g** [triniwiz/nativescript-image-cache-it#32]
### Which platform(s) does your issue occur on?
- Android tested

### Description

When I do 

    <ic:ImageCacheIt imageUri="{{ imgUrl }}" stretch="aspectFit" resize="400,400"/>

the height of the image is stripped according to the aspect ratio.
![screenshot_20180712_114857](https://user-images.githubusercontent.com/40174710/42626043-91230d8c-85c9-11e8-8bd3-e849507b5340.png)

However, when I do 

    <ic:ImageCacheIt imageUri="{{ imgUrl }}" stretch="aspectFit" resize="2000,2000"/>

the image is fit to the screen width (1200px), but white strips appear under and above. I'd expect the same behavior as above.
![screenshot_20180712_114443](https://user-images.githubusercontent.com/40174710/42625804-f98300c2-85c8-11e8-9ed4-17cd43e39dc1.png)

When I do

    <ic:ImageCacheIt imageUri="{{ imgUrl }}" stretch="none" width="80%" />

the image is resized to 80% of width but white space appears around. I'd expect sizing the width and height of the view accordingly, not padding the image to original size.
![screenshot_20180712_114654](https://user-images.githubusercontent.com/40174710/42625917-47a1b0d2-85c9-11e8-97b6-45f31c14de63.png)

**Comment by triniwiz** [comment]
Interesting find i'll check it out 🙂

**Comment by Tyg-g** [comment]
I found out that the situation totally changes when I set `myImageCacheItView.nativeView.setAdjustViewBounds(true);`.

**Comment by ShyshkovOleg** [comment]
Hi @Tyg-g where do you set `myImageCacheItView.nativeView.setAdjustViewBounds(true);` 
Could you provide a snipet?

**Comment by triniwiz** [comment]
fixed in the latest alpha
