### ISSUE TITLE
[ns-vue] aspectFill working like aspectFit

### ISSUE THREAD

**Issue by mennolp098** [triniwiz/nativescript-image-cache-it#33]
### Which platform(s) does your issue occur on?
- Android emulator Nexus 5X (android 7.0, CPU x86)
- iOS **not tested**

### Please, provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: "version": "4.1.1"
- Runtime(s): can't find them...
- Plugin(s): 
    "dependencies": {
    "nativescript-camera": "^4.0.2",
    "nativescript-image-cache-it": "^4.0.4",
    "nativescript-imagepicker": "^6.0.3",
    "nativescript-localize": "^3.0.5",
    "nativescript-pager": "^8.0.2",
    "nativescript-pulltorefresh": "^2.1.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-videoplayer": "^4.1.0",
    "nativescript-videorecorder": "^3.0.0-alpha.11",
    "nativescript-vue": "^1.3.1",
    "npm": "^6.2.0",
    "tns-core-modules": "^4.1.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.2.0",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
1. Add the template below to any existing Vue project.
2. Run the template and see the result.

results
- Magenta border is shown to fill the whole screen
- Image is shown to aspect fit instead of aspect fill

### Is there any code involved? 
```
<template>
  <Page class="page">
    <ActionBar class="action-bar" title="Test" flat="true">
      <NavigationButton text="Go Back" android.systemIcon="ic_menu_back" @tap="$router.back()"/>
    </ActionBar>

    <StackLayout>
        <ImageCacheIt resize="300,300" stretch="aspectFill" class="test" imageUri="http://via.placeholder.com/300x300"/>
    </StackLayout>

  </Page>
</template>

<style scoped>
    .test {
        height: 100%;
        width: 100%;
        border-width: 1pt;
        border-color: magenta;
    }
</style>

**Comment by triniwiz** [comment]
Have you tried `fill` ?

**Comment by Gytisla** [comment]
Same problem, with `fill` image disappears.

**Comment by uzarsalan** [comment]
Hi! Any suggestions on this issue?

**Comment by tam-duong** [comment]
It doesn't display anything

**Comment by triniwiz** [comment]
fixed in the latest alpha
