### ISSUE TITLE
placeHolder is white/blank

### ISSUE THREAD

**Issue by ukik** [triniwiz/nativescript-image-cache-it#34]
placeHolder="~/images/thumbnail-default-red.png" is white/blank

**Comment by Skintillion** [comment]
Having trouble with this as well.

**Comment by triniwiz** [comment]
Which platform ?

**Comment by Skintillion** [comment]
Android, and I can test iOS as well in a moment here. All plugins and NativeScript are current.


```
<i:ImageCacheIt 
              class="thread-image"
              stretch="aspectFit"  
              width="50"
              height="50"
              resize="50,50" 
              verticalAlignment="top"
              placeHolder="~/assets/loading.gif"
              errorHolder="~/assets/broken.png"
              imageUri="{{ image ? ('https://someurl/thumbnails/'+image) : '' }}"
              visibility="{{ image ? 'visible' : 'collapsed' }}"
              />
```

![image](https://user-images.githubusercontent.com/1521506/47395102-282c3300-d6da-11e8-9dd0-287085f2ebc3.png)


```
{
  "nativescript": {
    "id": "org.nativescript.testapp",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "description": "testapp",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "nativescript-camera": "^4.0.2",
    "nativescript-cardview": "^3.1.1",
    "nativescript-floatingactionbutton": "^4.1.4",
    "nativescript-geolocation": "^4.3.1",
    "nativescript-image-cache-it": "^4.0.7",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-platform-css": "^1.6.6",
    "nativescript-plugin-firebase": "^7.2.0",
    "nativescript-popup": "^1.5.0",
    "nativescript-pulltorefresh": "^2.1.1",
    "nativescript-ripple": "^2.1.0",
    "nativescript-textinputlayout": "^2.0.6",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^3.7.2",
    "nativescript-ui-sidedrawer": "^4.3.1",
    "tns-core-modules": "~4.2.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~0.16.0"
  },
  "readme": "Test App"
}
```

**Comment by triniwiz** [comment]
Can you try another image type for the placeholder

**Comment by Skintillion** [comment]
I tried the broken.png as well, no go. It's just blank. I can try something else if you prefer?

Going to try a jpg that's the exact size.

**Comment by triniwiz** [comment]
Thanks for the info I’ll look into it if you want you can try using an image from the resources directory

**Comment by Skintillion** [comment]
I tried with an exact size jpg as well, and I also forced the imageUri to fail but neither the placeHolder or errorHolder showed up.

iOS does show the placeHolder and errorHolder, however the gif is not animated.

**Comment by triniwiz** [comment]
Yeah gif is not supported yet

**Comment by Skintillion** [comment]
Made a table to help detail everything easier.

| Platform  | res://loading  nativescript documented method | res://loading.jpg | ~/assets/loading.jpg | gif |
| ------------- | ------------- |------------- |------------- |------------- |
| Android  | Crashes  | Blank | Blank | Blank |
| iOS  | Works  | Works | Works | Works but not animated |

**Comment by Skintillion** [comment]
Well your demo works for Android  (law.jpg shows up fine). However, when i try and duplicate your setup I get an error "Cannot read property 'placeholder' of undefined.

Which I believe is on this line:

`this.builder.placeholder(placeholder);`

Image is in `app\src\main\res\drawable\loading.jpg` so I know it exists and is transferred (I tested loading it with a standard Image loader)

I'll try and figure it out more tomorrow.

**Comment by Skintillion** [comment]
Demo worked fine, I kept getting crashes as noted above.

I fixed it with the PR I submitted. Now Android and iOS work great.

Thanks for the great plugin!

**Comment by NikhilAkorde** [comment]
> Demo worked fine, I kept getting crashes as noted above.
> 
> I fixed it with the PR I submitted. Now Android and iOS work great.
> 
> Thanks for the great plugin!



> Demo worked fine, I kept getting crashes as noted above.
> 
> I fixed it with the PR I submitted. Now Android and iOS work great.
> 
> Thanks for the great plugin!

how  you fixed this issue , can you explain how to do? 
because placeHolder image not display in my project.

**Comment by triniwiz** [comment]
@NikhilAkorde atm only `res://` uris are supported
