### ISSUE TITLE
Is Tap Event Supported?

### ISSUE THREAD

**Issue by b02505048** [triniwiz/nativescript-image-cache-it#36]
I tested it on iOS 12.1 simulator, it seems like not supporting `tap` event

Since `Image` inherited from `View` and it will listen to `tap` event, `ImageCacheIt` should also works with `tap` event, am I right?

Any idea?

**Comment by triniwiz** [comment]
If it’s not working in the view try the `on(‘tap’)` in code

**Comment by b02505048** [comment]
Thanks for replying @triniwiz, I end up with adding a `<StackLayout>` outside the `<ImageCacheIt />` and now it works!

**Comment by Whip** [comment]
Please add tap event via XML. Or if its already there, please look into it why its not working. I'm using iOS

**Comment by stevenspiel** [comment]
The tap event seems to work fine for me on Android, but nothing on iOS. Even when I add a listener on the element's loaded event, no luck.

**Comment by triniwiz** [comment]
Its fixed in https://github.com/triniwiz/nativescript-image-cache-it/commit/07cac8ac6a50e8a068d2355cc14a83bc1f75fa2a

**Comment by stevenspiel** [comment]
Working great for me using `4.1.1`!
