### ISSUE TITLE
Request: Support configurable Authorization header with image requests

### ISSUE THREAD

**Issue by yoat** [triniwiz/nativescript-image-cache-it#41]
My API secures image requests with Authorization headers (some Basic auth, others are Bearer token auth).  If you could allow a configurable string input to include with authorization headers I could use your plugin with my authenticated API.

Thanks for considering this request!

**Comment by Mafick** [comment]
I really need this feature too. This would just be awesome !

**Comment by triniwiz** [comment]
you can now set the headers per image request using the `headers` prop

**Comment by yoat** [comment]
Thanks @triniwiz !
