### ISSUE TITLE
Error when calling fetchItem

### ISSUE THREAD

**Issue by yonatann** [triniwiz/nativescript-image-cache-it#42]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
When tryin to call fetchItem an error occurs:
Uncaught (in promise): TypeError: Cannot read property 'Callback' of undefined

### Which platform(s) does your issue occur on?
- Android
- Platform 28
- Both emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.0.3
- Cross-platform modules: 5.0.5
- Runtime(s): 5.0.0
- Plugin(s): 
"dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@auth0/angular-jwt": "^2.0.0",
    "angular-jwt": "^0.1.10",
    "http-status-codes": "^1.3.0",
    "jwt-decode": "^2.2.0",
    "moment": "^2.22.2",
    "nativescript-angular": "^7.0.2",
    "nativescript-background-http": "^3.3.0",
    "nativescript-calendar": "^2.0.1",
    "nativescript-camera": "^4.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-facebook": "^2.2.4",
    "nativescript-gif": "^4.0.1",
    "nativescript-globalevents": "^1.2.2",
    "nativescript-image-cache-it": "^4.1.0",
    "nativescript-imagepicker": "^6.0.4",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-pager": "^8.0.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-appsflyer": "^1.0.14",
    "nativescript-plugin-firebase": "^7.4.3",
    "nativescript-social-share": "^1.5.0",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-listview": "^5.0.0",
    "nativescript-ui-sidedrawer": "^5.0.0",
    "nativescript-urlhandler": "^1.2.2",
    "nativescript-videoplayer": "^4.0.4",
    "nativescript-zxing": "1.5.7",
    "reflect-metadata": "~0.1.8",
    "rollbar": "^2.5.0",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.0.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.0.0",
    "@ngtools/webpack": "~7.0.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.3.0",
    "lazy": "1.0.11",
    "nativescript": "^5.0.3",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.18.1",
    "tns-platform-declarations": "^5.0.5",
    "tslint": "~5.10.0",
    "typescript": "^3.2.2"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Simply call the fetchItem API

### Is there any code involved? 
import { ImageCacheIt } from 'nativescript-image-cache-it';
ImageCacheIt.fetchItem(URL);

When I used the debugger to investigate the issue the problem seems to be that com.squareup.picasso3 is not defined.
I checked and com.squareup.picasso (without 3) is defined so perhaps it is a dependancies problem.

See call stack below:
JS: TypeError: Cannot read property 'Callback' of undefined
JS:     at file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js:248:83
JS:     at new ZoneAwarePromise (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)
JS:     at Function.ImageCacheIt.fetchItem (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js:246:16)
JS:     at file:///data/data/com.moodapplication/files/app/activities/story/story.component.js:108:64
JS:     at ZoneDelegate.invoke (file:///data/data/com.moodapplication/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:26)
JS:     at Object.onInvoke (file:///data/data/com.moodapplication/files/app/tns_modules/@angular/core/bundles/core.umd.js:14111:37)
JS:     at ZoneDelegate.invoke (file:///data/data/com.moodapplication/files/app/tns_module...

**Comment by stevenspiel** [comment]
Also experiencing this with v 4.1.0

**Comment by Jarrich** [comment]
Has anyone found a solution for this issue?

**Comment by MihkelBaranov** [comment]
I was able to get it working by replacing

https://github.com/triniwiz/nativescript-image-cache-it/blob/master/src/image-cache-it.android.ts#L209

with

```
ImageCacheIt.getPicasso().load(image).into(new com.squareup.picasso.Target({
	onBitmapLoaded(bitmap, from) {
		resolve(bitmap);
	},
	onBitmapFailed(errorDrawable) {
		reject();
	},
	onPrepareLoad(placeHolderDrawable) { }
}));
```

and 

https://github.com/triniwiz/nativescript-image-cache-it/blob/master/src/image-cache-it.android.ts#L234

with

```
ImageCacheIt.getPicasso().load(image).fetch(new com.squareup.picasso.Callback({....
```
