### ISSUE TITLE
Crashing on iOS (Invalid value: right) 

### ISSUE THREAD

**Issue by fhackenb** [triniwiz/nativescript-image-cache-it#46]
### Which platform(s) does your issue occur on?
- {N} w/ angular for iOS (emulator & device)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.1
- Cross-platform modules: 5.2.2
- Runtime(s): tns-ios: 5.2.0
- Plugin(s): 
 "dependencies": {
    "@angular/animations": "^7.2.0",
    "@angular/common": "^7.2.0",
    "@angular/compiler": "^7.2.0",
    "@angular/core": "^7.2.0",
    "@angular/forms": "^7.2.0",
    "@angular/http": "^7.2.0",
    "@angular/platform-browser": "^7.2.0",
    "@angular/platform-browser-dynamic": "^7.2.0",
    "@angular/router": "^7.2.0",
    "amazon-cognito-identity-js": "^3.0.7",
    "aws-sdk": "^2.413.0",
    "nativescript-angular": "^7.2.2",
    "nativescript-appversion": "^1.4.1",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-bluetooth": "^1.3.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-fontawesome": "^1.0.0",
    "nativescript-geolocation": "^4.3.1",
    "nativescript-image-cache-it": "^4.1.2",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-keyboardshowing": "^1.0.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ng2-fonticon": "^1.3.4",
    "nativescript-nodeify": "^0.8.0",
    "nativescript-numeric-keyboard": "^4.2.0",
    "nativescript-orientation": "^2.2.0",
    "nativescript-print-star": "file:nativescript-print-star-0.1.7.tgz",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-secure-storage": "^2.3.0",
    "nativescript-sentry": "^1.5.1",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-sqlite-commercial": "file:commercial-sqlite-latest/nativescript-sqlite-commercial-1.3.2.tgz",
    "nativescript-sqlite-encrypted": "file:commercial-sqlite-latest/nativescript-sqlite-encrypted-1.4.0.tgz",
    "nativescript-square-plugin": "^1.0.5",
    "nativescript-square-reader": "^1.0.6",
    "nativescript-star-printer": "^1.2.1",
    "nativescript-tappy": "^1.0.6",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-core": "^2.0.0",
    "nativescript-ui-listview": "^5.2.0",
    "nativescript-ui-sidedrawer": "^4.3.1",
    "nativescript-urlhandler": "^1.2.2",
    "nativescript-uuid": "0.0.1",
    "raven-js": "^3.27.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "tns-core-modules": "^5.2.2",
    "tns-platform-declarations": "^4.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^7.2.0",
    "@ngtools/webpack": "^7.2.0",
    "@types/chai": "^4.1.7",
    "@types/mocha": "^5.2.6",
    "@types/node": "^10.12.29",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^4.5.0",
    "copy-webpack-plugin": "^5.0.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "^3.0.2",
    "lazy": "1.0.11",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "^1.18.0",
    "mocha-multi": "^1.0.1",
    "nativescript-dev-appium": "^5.0.0",
    "nativescript-dev-typescript": "^0.7.4",
    "nativescript-dev-webpack": "^0.20.2",
    "nativescript-worker-loader": "^0.9.5",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "string-replace-loader": "^2.1.1",
    "terser-webpack-plugin": "^1.2.3",
    "ts-loader": "^5.3.3",
    "tslint": "~5.8.0",
    "typescript": "^3.1.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "webpack": "^4.20.2",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-sources": "^1.3.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 

I have a RadListView with some items in it and when I attempt to use this plugin the app crashes. Adding some debug logic, I found the Error:

```
TypeError: undefined is not a function (near '...this.nativeView.sd_setImageWithURLPlaceholderImageCompleted...')

```
The source is:

```
this.nativeView.sd_setImageWithURLPlaceholderImageCompleted(src, this.placeHolder
                        ? imageSrc.fromFileOrResource(this.placeHolder).ios
                        : null, function (p1, p2, p3, p4) {
                            _this.isLoading = false;
                            if (p2 && _this.errorHolder) {
                                var source = imageSrc.fromFileOrResource(_this.errorHolder);
                                _this.nativeView.image = source ? source.ios : null;
                            }
                        });

```

My code is:
```
<ImageCacheIt stretch="aspectFit" resize="150,150" placeHolder="res://user_3x" [imageUri]="item.imageUrl" *ngIf="item.imageUrl"></ImageCacheIt>
```

I've tried w/ and w/o the placeholder and resize but I'm consistently getting the same error

Any ideas?

**Comment by triniwiz** [comment]
fixed in the latest alpha
