### ISSUE TITLE
PlaceHolder not showing on Android

### ISSUE THREAD

**Issue by javierpal** [triniwiz/nativescript-image-cache-it#49]
We have this problem again, https://github.com/triniwiz/nativescript-image-cache-it/issues/34
iOS is working fine!, but for some reason in android there is no placeHolder image, just the internet image i'm using.
I'm using this code

`<ImageCacheIt  placeHolder="~/assets/question_mark.png" 
            errorHolder="~/assets/question_mark.png"
            stretch="none" class="thumb img-rounded" [src]="auction.item.icon">
</ImageCacheIt>`

i been using this line `~/assets/question_mark.png` to get assets from the assets folder I created using this method: https://github.com/NativeScript/nativescript-schematics/issues/33#issuecomment-427688796 works fine in both platforms but still image cache it does not. can be me, or maybe a plugin problem? 

PD: "res//:" does not work in iOS and leads to Crashes

here is my package.json

{
    "nativescript": {
        "tns-ios": {
            "version": "5.1.1"
        },
        "tns-android": {
            "version": "5.1.0"
        }
    },
    "dependencies": {
        "@angular/animations": "~7.1.0",
        "@angular/common": "~7.1.0",
        "@angular/compiler": "~7.1.0",
        "@angular/core": "~7.1.0",
        "@angular/forms": "~7.1.0",
        "@angular/http": "~7.1.0",
        "@angular/platform-browser": "~7.1.0",
        "@angular/platform-browser-dynamic": "~7.1.0",
        "@angular/router": "~7.1.0",
        "moment": "^2.24.0",
        "nativescript-admob": "^3.3.2",
        "nativescript-angular": "~7.1.0",
        "nativescript-checkbox": "^3.0.3",
        "nativescript-image-cache-it": "^5.0.0-alpha.3",
        "nativescript-localize": "^4.2.0",
        "nativescript-purchase": "^2.0.13",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-toasty": "^2.0.0",
        "reflect-metadata": "~0.1.12",
        "rxjs": "~6.3.0",
        "tns-core-modules": "~5.1.0",
        "zone.js": "~0.8.26"
    },
    "devDependencies": {
        "@angular/compiler-cli": "^8.0.3",
        "@nativescript/schematics": "~0.5.0",
        "@ngtools/webpack": "~7.1.0",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "^0.24.1",
        "typescript": "3.4.5",
        "uglifyjs-webpack-plugin": "^2.1.3"
    },
    "readme": "NativeScript Application"
}

**Comment by kshipra-shelke** [comment]
Any update on this Issue?

**Comment by manijak** [comment]
Seeing the same thing on iOS (both placeHolder and errorHolder not showing). Running NS 6.0
