### ISSUE TITLE
Nativescript Vue.JS use

### ISSUE THREAD

**Issue by Skintillion** [triniwiz/nativescript-image-cache-it#50]
Has anyone had any luck getting this working with VueJS?

**Comment by AlexBa** [comment]
Yes, I have a working version.

Example:
```
import { ImageCacheIt } from "nativescript-image-cache-it/image-cache-it.ios";

Vue.registerElement('ImageCacheIt', () => ImageCacheIt);
```

But at the moment, I only use IOS. Maybe you can import the module without the ```image-cache-it.ios``` suffix to make it work for Android & IOS.

**Comment by triniwiz** [comment]
```ts
import ImageCacheIt from 'nativescript-image-cache-it/vue'
Vue.use(ImageCacheIt)
```
