### ISSUE TITLE
'manager.imageCache.defaultCachePathForKey' is undefined

### ISSUE THREAD

**Issue by asharghi** [triniwiz/nativescript-image-cache-it#51]
I'm getting defaultCachePathForKey is undefined in line 196 of image-cache-it.ios.js. I changed it to cachePathForKey and that works. 

I'm on version 5.0.0-alpha.3 with SDWebImage 5.1.0

- Phone X iOS 12.4.1
- CLI: 6.0.3
- Runtime tns-ios: 6.0.2

<img width="628" alt="Screenshot 2019-09-18 at 01 32 53" src="https://user-images.githubusercontent.com/9407896/65069830-b3c74600-d9b5-11e9-915a-21d55ed2dc52.png">

**Comment by triniwiz** [comment]
pr away 🙂🙃

**Comment by asharghi** [comment]
Fixed with https://github.com/triniwiz/nativescript-image-cache-it/pull/52
