### ISSUE TITLE
Stretch broken since implementing default scaling

### ISSUE THREAD

**Issue by joshcomley** [triniwiz/nativescript-image-cache-it#53]
### Make sure to check the demo app(s) for sample usage 
Done

### Make sure to check the existing issues in this repository 
Done

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Using stretch no longer works since:
https://github.com/triniwiz/nativescript-image-cache-it/commit/4e77218b6f33bd77699e3236d28ca21e3f79d223

### Which platform(s) does your issue occur on?
- Android
- Android 8.1.0
- Samsung Galaxy Tab A (2016) - SM-T585

### Please, provide the following version numbers that your issue occurs with:
5.0.0-alpha.17

- CLI: 6.1.2
- Cross-platform modules: 6.1.1
- Runtime(s): 6.1.2

### Is there any code involved? 

Here is sample code working before the change but not now:

    <StackLayout>
        <ImageCacheIt src="https://s3.amazonaws.com/under10/website/2014/07/level-1-2-3-image.jpg" stretch="aspectFit"
            [width]="100" [height]="100">
        </ImageCacheIt>
        <ImageCacheIt src="https://s3.amazonaws.com/under10/website/2014/07/level-1-2-3-image.jpg" stretch="aspectFill"
            [width]="100" [height]="100">
        </ImageCacheIt>
        <ImageCacheIt src="https://s3.amazonaws.com/under10/website/2014/07/level-1-2-3-image.jpg" stretch="none"
            [width]="100" [height]="100">
        </ImageCacheIt>
        <ImageCacheIt src="https://s3.amazonaws.com/under10/website/2014/07/level-1-2-3-image.jpg" stretch="fill"
            [width]="100" [height]="100">
        </ImageCacheIt>
    </StackLayout>

Since using the default scaling and not transforms, the above code renders the same left hand portion of the image in each instance.

**Comment by triniwiz** [comment]
Do you have a before and after screenshot ?

**Comment by triniwiz** [comment]
This is what I get after applying my fix ![image](https://user-images.githubusercontent.com/6695919/66483705-9bf25780-ea73-11e9-9b56-94c37b56ae0a.png)

**Comment by joshcomley** [comment]
Sorry yes I should have attached screenshots, but the pic you've attached after your fix is identical to what I get if I manually patch the file in `node_modules` to play the old way (with transforms). I'm curious, did you reapply transforms or get the scaling on `ImageView` working? That was quick!

**Comment by joshcomley** [comment]
For reference here are the screenshots:

## Before:
![Screenshot_20191009-141442_isite](https://user-images.githubusercontent.com/820534/66484725-7418e900-ea9f-11e9-9a2f-fe475bdcae06.jpg)

## After:
![Screenshot_20191009-141159_isite](https://user-images.githubusercontent.com/820534/66484736-7c712400-ea9f-11e9-9387-9cdec7d695d9.jpg)

**Comment by triniwiz** [comment]
I included the transformation

**Comment by joshcomley** [comment]
Also, thanks for the plugin
