### ISSUE TITLE
Border radius not applied on place/errorHolder images (Android)

### ISSUE THREAD

**Issue by jpierront** [triniwiz/nativescript-image-cache-it#55]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Border radius are not applied on placeholder and errorHolder images on Android.

### Which platform(s) does your issue occur on?
- Android
- 8.1 (Not tester on other version)
- Emulator
- Angular

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.1.1
- Runtime: 6.1.1
- nativescript-image-cache-it: 5.0.0-alpha.18

### Please, tell us how to recreate the issue in as much detail as possible. 
Use border-radius on ImageCacheIt with a missing or wrong "src".

**Comment by triniwiz** [comment]
fixed: https://github.com/triniwiz/nativescript-image-cache-it/commit/4eb8406b0ed212d10ebe4595bf8819fffe878437

**Comment by jpierront** [comment]
Hello thx for the patch!

I using it in an app with a sidedrawer.
In the menu, placeholder are rounded, in the main content the placeholder are still square. (Very strange)

Be careful, now image always have a black border (I need a rounded image without any border)

Sorry not to be able to give your more details but for the moment I switched to another plugin.

**Comment by triniwiz** [comment]
Yeah thats fixed already just not released
