### ISSUE TITLE
Getting 'Cannot read property 'glide' of undefined' when using with vue.js

### ISSUE THREAD

**Issue by Alzy** [triniwiz/nativescript-image-cache-it#56]
I just installed the plugin as described in the read me and am getting the error quoted below whenever I run `tns preview --bundle`. For reference, here is my main.js:

```
import Vue from 'nativescript-vue'
import App from './components/App'

import ImageCacheIt from 'nativescript-image-cache-it/vue'

Vue.use(ImageCacheIt)

import store from './store'

  
// Prints Vue logs when --env.production is *NOT* set while building
Vue.config.silent = (TNS_ENV === 'production')

new Vue({
  store,
  render: h => h('frame', [h(App)])
}).$start()

```

Any ideas how to fix this?..

### Which platform(s) does your issue occur on?
- Android
- Windows 10
- Javascript with Vue (no typescript)

### The Error Log

> Calling js method getView failed
> TypeError: Cannot read property 'glide' of undefined
> 
> StackTrace:
> 	ImageCacheIt.getGlide(file:///data/data/org.nativescript.preview/files/app/vendor.js:24834:36)
> 	at ImageCacheIt.initNativeView(file:///data/data/org.nativescript.preview/files/app/vendor.js:24887:26)
> 	at ViewBase.setNativeView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:548:12)
> 	at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:527:10)
> 	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:534:13)
> 	at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:20)
> 	at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:1010:10)
> 	at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:10)
> 	at ViewBase._addViewCore(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:432:12)
> 	at ViewBase._addView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:421:10)
> 	at ListViewAdapter.getView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js:269:24)
> 	at com.tns.Runtime.callJSMethodNative(Native Method)
> 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
> 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
> 	at com.tns.gen.android.widget.BaseAdapter_view_197_26_ListViewAdapter.getView(BaseAdapter_view_197_26_ListViewAdapter.java:39)
> 	at android.widget.AbsListView.obtainView(AbsListView.java:2373)
> 	at android.widget.ListView.onMeasure(ListView.java:1285)
> 	at android.view.View.measure(View.java:23187)
> 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
> 	at org.nativescript.widgets.VerticalScrollView.onMeasure(VerticalScrollView.java:147)
> 	at android.view.View.measure(View.java:23187)
> 	at org.nativescript.widgets.FlexboxLayout.measureVertical(FlexboxLayout.java:760)
> 	at org.nativescript.widgets.FlexboxLayout.onMeasure(FlexboxLayout.java:375)
> 	at android.view.View.measure(View.java:23187)
> 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
> 	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
> 	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
> 	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
> 	at android.view.View.measure(View.java:23187)
> 	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
> 	at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
> 	at android.view.View.measure(View.java:23187)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
> 	at android.view.View.measure(View.java:23187)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
> 	at android.view.View.measure(View.java:23187)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at android.view.View.measure(View.java:23187)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
> 	at android.view.View.measure(View.java:23187)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:751)
> 	at android.view.View.measure(View.java:23187)
> 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2756)
> 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1605)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1889)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1493)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7283)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
> 	at android.view.Choreographer.doFrame(Choreographer.java:696)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6912)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.androi

d.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by triniwiz** [comment]
try cleaning the project an building again

**Comment by Alzy** [comment]
Turns out it will only work when physically plugged into the device. `tns preview` will not work per the documentation as plugins are not transferred using that method. Thank you.
