### ISSUE TITLE
aspectFit stretch glitch

### ISSUE THREAD

**Issue by Alzy** [triniwiz/nativescript-image-cache-it#57]
I'm using this plugin in my nativescript-vue app to cache images from my events listing site and display them in a list. I have them inside FlexboxLayouts with stretch set to aspectFit. Originally, if I did not set a height my image would appear like this [LINK](https://ibb.co/ZNk1yCn
). I thought maybe setting a height or width would fix the problem but not really as you can see here: [LINK](https://ibb.co/7jb0Nsk) Images which are already taller than the height I set will simply be cropped, otherwise they stretch in that really glitchy manner to fill the container. Without a set height they just seem to stretch to some arbitrary distance... Thoughts?

Sidenote: I can confirm this glitch did not happen when I was using Image tags with aspectFit. The issue started immediately after implementing ImageCacheIt tags

### Relevant code below

```
    <FlexboxLayout backgroundColor="black" color="white" flexDirection="column">      
      <!-- Events List -->
      <ScrollView flexGrow="1">
        <ListView for="event in events" minHeight="1920" flexGrow="1" class="eventsList">


          <v-template>
            <!-- event listing -->
            <FlexboxLayout flexDirection="row" width="100%">
              <FlexboxLayout flexDirection="column" class="eventImageWrapper" width="30%" @tap="eventTap(event)">
                <ImageCacheIt :src="'https://sfvm.la'+event.image" class="eventImage" stretch="aspectFit" height="100%"/>
              </FlexboxLayout>
              <FlexboxLayout flexDirection="column" class="eventDetails" width="70%" @tap="eventTap(event)">
                <Label :text="event.name" fontSize="22" textWrap="true"/>
                <Label :text="(event.price == '0.00' ? 'FREE' : '$'+event.price)" />
                <Label :text="event.city" />
              </FlexboxLayout>
            </FlexboxLayout>
          </v-template>


        </ListView>
      </ScrollView>
    </FlexboxLayout>
```

### Which platform(s) does your issue occur on?
- Android
- NativeScript Vue

**Comment by triniwiz** [comment]
Fixed but not released yet .... i'll try to push it soon

**Comment by Alzy** [comment]
> Fixed but not released yet .... i'll try to push it soon

Awesome! Any idea approximately when it will be released?

**Comment by triniwiz** [comment]
After some upgrading a feature I recently added was not added back to android ... so that's the delay 😃

**Comment by Alzy** [comment]
> Fixed but not released yet .... i'll try to push it soon

Aw man, I'll keep an eye out for the update in the meantime. Thank you. Godspeed!
