### ISSUE TITLE
TypeError: Cannot read property 'picasso' ...

### ISSUE THREAD

**Issue by andreasotto** [triniwiz/nativescript-image-cache-it#6]
Installed from documentation using

`# npm i nativescript-image-cache-it`

put into xml Page declaration:

`xmlns:i="nativescript-image-cache-it"`

put into markup:

`<i:ImageCacheIt stretch="aspectFill" imageUri="{{ titleImg }}" />`

imported in .ts file

`import {ImageCacheIt} from 'nativescript-image-cache-it';`

When the app is run, the following error occurs:

TypeError: Cannot read property 'picasso' of undefined File: "../app/tns_modules/nativescript-image-cache-it/image-cache-it.js", line: 71, colum: 40

**Comment by FewKinG** [comment]
same here :(

**Comment by triniwiz** [comment]
i will need to look into this

**Comment by FewKinG** [comment]
@andreasotto I was using the image-cache plugin with nativescript on angular2, but that doesn't necessarily make a difference.
Did you completely rebuild your project after adding the plugin? What I did was having the livesync running and after installing the plugin I just stopped it an reran `tns livesync -w android` thinking this would also rebuild everything.

When I started working on it again a few days later I actually performed a `tns run android` instead, which did a complete build and suddenly everything worked fine. Don't know if this really was the key or if I missed something else. But I found this to be critical for other changes concerning native Java too. When you for example extend native Java classes inside your JS/TS code, you always have to rebuild, syncing doesn't suffice.

**Comment by RyanSMurphy** [comment]
this is an issue, even after rebuild. In angular 2 nativescript I registered the element in my component: 

registerElement("ImageCacheIt", () => require("nativescript-image-cache-it").ImageCacheIt);

and then used it in my view and it gives me the same picasso error.

**Comment by RyanSMurphy** [comment]
@andreasotto @triniwiz I can confirm that @FewKinG is correct, this will require a full rebuild. 

On angular 2, register the element via: 

registerElement("ImageCacheIt", () => require("nativescript-image-cache-it").ImageCacheIt);

and use it in the view like so: 

<ImageCacheIt [imageUri]="item.image" class="mainImage" stretch="aspectFill"></ImageCacheIt>

**Comment by ADjenkov** [comment]
Same error here (Android + JavaScript + {N] 2.3.0) 

TypeError: Cannot read property 'picasso' of undefined File: "../app/tns_modules/nativescript-image-cache-it/image-cache-it.js", line: 71, colum: 40

**Comment by triniwiz** [comment]
@ADjenkov did you rebuild the app after adding the plugin ?

**Comment by ADjenkov** [comment]
@triniwiz  Yes. It even rebuilds automatically everytime a new package is installed I think.

**Comment by triniwiz** [comment]
@ADjenkov are you using livesync by chance ?

**Comment by ADjenkov** [comment]
Yes I am..But when I run `tns livesync android` and there is a new depencency added (in this case **nativescript-image-cache-it**) a new build is triggered from the scratch. But I'll try to use the plugin over a brand new app with fresh build later :)

**Comment by FewKinG** [comment]
Like I said, I was using `tns livesync` too, but for me this doesn't trigger a complete rebuild. It seems to do more than the continuous livesync but less than a `build` or `run` command.

When I for example in one of my typescript source files change a Java class that I am using in my app, the changes won't be recognized until I do a `build`. livesync doesn't cut it here.

**Comment by triniwiz** [comment]
some info on the problem https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/
