### ISSUE TITLE
XML Image Event

### ISSUE THREAD

**Issue by mudlabs** [triniwiz/nativescript-image-cache-it#61]
It would be good to have an event for handling image loading bound to the `xml`. Something like this;
```xml
<i:ImageCacheIt placeHolder="placeholder.png" errorHolder="errorholder.png" src="propert_image.png" cacheIt="'onImageCacheIt"/>
```
```js
function onImageCacheIt(args) {
    const imageView = args.object;
    args.error 
      ? console.log("The image could not be loaded", args.error.reason)
      : console.log("The image was loaded successfully");
}
exports.onImageCacheIt = onImageCacheIt;
```

The code-behind methods for loading and removing images from cache are all promise based so we have error handling. But if you want to set the request from `xml` there's no mechanism for getting feedback related to the image state.

**Comment by triniwiz** [comment]
Sounds interesting

**Comment by triniwiz** [comment]
there are 4 new events `loadStart` `error` `loadEnd` `progress`
