### ISSUE TITLE
Cannot set individual corner border radius on Android

### ISSUE THREAD

**Issue by amarseelam** [triniwiz/nativescript-image-cache-it#64]
I am trying to set the border radius of  left-top and right-top corners of my image using CSS.

I am using the below CSS block

```
.image-top-rounded{
    border-top-left-radius:10;
    border-top-right-radius:10;
    border-width:0;
}
```

This works as expected on iOS.
On Android I do not see the corners rounded.
It works fine when I use the  border-radius to round all corners.

✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.2.2 version and is up to date.
✔ Component tns-core-modules has 6.2.3 version and is up to date.
✔ Component tns-android has 6.2.0 version and is up to date.
✔ Component tns-ios has 6.2.0 version and is up to date.

**Comment by triniwiz** [comment]
If you try setting the border-width > 0?

**Comment by amarseelam** [comment]
I tried setting border-width to 1 and it did not help.

**Comment by triniwiz** [comment]
What about including a color ? Just trying to a quick find of the bug 🙂

**Comment by triniwiz** [comment]
fixed: https://github.com/triniwiz/nativescript-image-cache-it/commit/936ecd48fd4ea0c49ac1d1d529879c654ce0f45c
