### ISSUE TITLE
The component not load properly the url images when it receive the url from bindable properties

### ISSUE THREAD

**Issue by anodal88** [triniwiz/nativescript-image-cache-it#7]
For example:
this work fine
`<i:ImageCacheIt stretch="aspectFit"  centerCrop="false" resize="300,300" placeHolder="~/assets/images/ph.png" errorHolder="~/assets/images/broken.png" imageUri="http://screenrant.com/wp-content/uploads/The-Flash-vs-the-Reverse-Flash.jpg"/>`

this not
`<i:ImageCacheIt stretch="aspectFit"  centerCrop="false" resize="300,300" placeHolder="~/assets/images/ph.png" errorHolder="~/assets/images/broken.png" imageUri="{{url}}"/>`
The load time is reduced and after 1 second approximately the component set broken picture.

Thank you.

**Comment by ADjenkov** [comment]
@triniwiz  Binding `imageUri` is not working.
Also tested on {N} 2.5 + Angular 2

**Comment by triniwiz** [comment]
will update and push a new build asap 😄

**Comment by triniwiz** [comment]
Should be working fine with v2
