### ISSUE TITLE
enableAutoMM is not a function

### ISSUE THREAD

**Issue by Whip** [triniwiz/nativescript-image-cache-it#70]
### Which platform(s) does your issue occur on?
- Android 
- Android 10 
- Nokia 6.1 device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.3
- Cross-platform modules: 6.3.2
- Runtime(s): 6.3.1
- Plugin(s): 
```
"dependencies": {
    "@nativescript/theme": "~2.2.1",
    "@nstudio/nativescript-cardview": "1.0.0",
    "nativescript-accordion": "6.0.0-beta.2",
    "nativescript-image-cache-it": "5.0.0-beta.6",
    "nativescript-material-icons": "1.0.3",
    "nativescript-toasty": "3.0.0-alpha.2",
    "tns-core-modules": "~6.3.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.4.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I followed the instructions in the readme and got error "ImageCacheIt.enableAutoMM is not a function"

### Is there any code involved? 
 App.js
```
const ImageCacheIt = require('nativescript-image-cache-it');
ImageCacheIt.enableAutoMM();
application.run({ moduleName: "app-root" });
```

Product-page.xml
```
<Page navigatingTo="onNavigatingTo" loaded="onLoaded" class="page" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:i="nativescript-image-cache-it">
    <ListView items="{{ products }}" separatorColor="#CCC" class="m-t-10" row="1">
    	<ListView.itemTemplate>
	  		<GridLayout columns="100,*">
          <i:ImageCacheIt column="0" stretch="aspectFill" resize="100,100" placeHolder="~/images/loading.jpg" errorHolder="~/images/loading.jpg" src="{{ image }}"/>
          <StackLayout column="1">
  	  			<Label text="{{ name }}"></Label>
  	  		</StackLayout>
  	  	</GridLayout>
    	</ListView.itemTemplate>
    </ListView>
</Page>
```

**Comment by triniwiz** [comment]
please try updating to the latest version

**Comment by Whip** [comment]
I'm using Sidekick and its only letting me update upto Beta 9. The issue is not fixed with that and I don't have the option to update to Beta 10

**Comment by Whip** [comment]
Hey @triniwiz I've updated to Beta 14 and I still have the error.

PS - Deleted platforms and node_modules folder before rebuilding.
