### ISSUE TITLE
Issues on Android image stretch & nodpi images

### ISSUE THREAD

**Issue by manijak** [triniwiz/nativescript-image-cache-it#73]
### Make sure to check the demo app(s) for sample usage 
done 

### Make sure to check the existing issues in this repository 
done 

### If the demo apps cannot help and there is no issue for your problem, tell us about it
To start with: Using iOS none of these issues are present, same goes for the stock `Image` plugin.

1) On Android, all images are stretched full width & height without keeping the aspect, no matter what stretch type used. I had to set both width & height for it to  apply the proper stretch type. 

2) Also only on Android, the plugin is not able to load local images located in `App_Resources/res/drawable-nodpi/` folder. 

### Which platform(s) does your issue occur on?
- Android
- Android 28 & 29 
- Emulator

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.4.1
- Cross-platform modules: 6.4.2
- Runtime(s): 6.4.1

### Please, tell us how to recreate the issue in as much detail as possible. 
```xml
<GridLayout columns="*,48,*" rows="50,*">
    <ic:ImageCacheIt col="0" row="0" src="{{ remoteImage1 }}" stretch="aspectFit" />
    <ic:ImageCacheIt col="1" row="0" src="res://local_image_nodpi_folder" stretch="aspectFit" height="26" />
    <ic:ImageCacheIt col="2" row="0" src="{{ remoteImage2 }}" stretch="aspectFit" />                     
</GridLayout>
```

**Comment by mennolp098** [comment]
I have the same issue, none of the stretch types seem to work.
I tried aspectFit and aspectFill on different images and none of them work. It only works when setting specific height and width.

**Comment by oneWaveAdrian** [comment]
Anybody found a solution to this yet? Same problem on my android version at the moment. A set height is unfortunately not an option in my case since the app involves a list of both, portrait and landscape pictures generated by user...

**Comment by triniwiz** [comment]
It’s the way the view is handling setting up for borders (scaling to fit the view size)  ... feel free to try w/o borders

**Comment by oneWaveAdrian** [comment]
@triniwiz thanks for taking a look so quickly!
For me `rows="auto"` and a correct `row` definition seems to work now.
Had no borders set for the element.

**Comment by trangbtm31** [comment]
I have the same issue too, is it fixed yet? Or please give me a solution, I need something like stretch="aspectFill" or object-fit:"cover" CSS to get the center of the image  in a square

**Comment by triniwiz** [comment]
Try removing the borders from the image then wrap said image in a container e.g grid finally add the border to the said container

**Comment by manijak** [comment]
What type of borders are we talking about here?

**Comment by triniwiz** [comment]
So atm any border apply to the view may cause any issue 🙂

**Comment by manijak** [comment]
Yeah I have never done that to any image, this behavior is visible on the image-plugin without any added borders...

**Comment by triniwiz** [comment]
Ah thanks will find a solution soon

**Comment by asharghi** [comment]
I'm having trouble with setting the width automatically. On both Android and iOS I have to specify the width and height, or else nothing is shown. Tried all the stretch modes and placing the image inside a GridLayout, without any luck. How can I achieve height="100%" and width="auto"?
