### ISSUE TITLE
Width in percent or "auto" does not work

### ISSUE THREAD

**Issue by asharghi** [triniwiz/nativescript-image-cache-it#76]
### Make sure to check the demo app(s) for sample usage 
Done

### Make sure to check the existing issues in this repository 
Done

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both: Both
- iOS/Android versions: iOS 13.2
- emulator or device. What type of device? Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 5.0.0-beta.20
- Runtime(s): 6.5.0
- Plugin(s): 5.0.0-beta.20

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
Width must be specified for the image to be shown. Not setting the width should behave as "auto", but right now it isn't.

 I have tried %, dpi and empty height and that works as expected, but for width you must set it to a specified dpi. Please take a look at example code under.

### Is there any code involved? 
No image is shown:
```
<StackLayout height="100%" width="100%">
        <ImageCacheIt height="100" stretch="none" :src="image.imageUrl" />
</StackLayout>
```

No image is shown:
```
<StackLayout height="100%" width="100%">
        <ImageCacheIt  height="100%" width="100%"  stretch="none" :src="image.imageUrl" />
</StackLayout>
```

A part of image is shown as expected:
```
<StackLayout height="100%" width="100%">
        <ImageCacheIt  height="100%" width="100"  stretch="none" :src="image.imageUrl" />
</StackLayout>
```

**Comment by asharghi** [comment]
@triniwiz Could you please test this?

**Comment by asharghi** [comment]
@triniwiz Any plans on giving this repo a little more love?

**Comment by triniwiz** [comment]
Soon it will get some for the {N} 7 release coming

**Comment by triniwiz** [comment]
fixed in the latest update
