### ISSUE TITLE
Latest version does not compile on Angular 9 when AOT is enabled

### ISSUE THREAD

**Issue by atbe** [triniwiz/nativescript-image-cache-it#78]
### Which platform(s) does your issue occur on?
- Both 
- iOS/Android all versions 

### Please, provide the following version numbers that your issue occurs with:

The issue is occuring on version `6.0.0`. I have not confirmed the issue on lower versions but I assume it would be the same.

### Please, tell us how to recreate the issue in as much detail as possible. 

I have created a bare-bones project here https://github.com/atbe/nativescript-image-cache-it-aot-issue which can be used to reproduce this issue.

To reproduce the issue:

1. Clone the above repo
2. Run `yarn install`
3. Run `tns build android --env.aot`

If you perform step 3 without the `--env.aot`, the project compiles fine.

The error message that is printed says:

```
ibrahimahmed@AbesMacbookFro ~/code/nativescript-gif-aot-issue                                                                                                                              [19:36:22]
> $ tns build android --env.aot                                                                                                                                                           [±master ●]
Preparing project...
Hash: 27b59a136ec398a38a9d
Version: webpack 4.42.0
Time: 4513ms
Built at: 07/28/2020 7:37:16 PM
              Asset       Size   Chunks             Chunk Names
          bundle.js    153 KiB   bundle  [emitted]  bundle
       package.json  112 bytes           [emitted]
         runtime.js   13.9 KiB  runtime  [emitted]  runtime
tns-java-classes.js    0 bytes           [emitted]
          vendor.js    5.3 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[./app.scss] 120 KiB {bundle} [built]
[./main.tns.ts] 1.16 KiB {bundle} [built]
[./package.json] 104 bytes {bundle} [optional] [built]
    + 323 hidden modules

ERROR in node_modules/nativescript-image-cache-it/angular/index.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-image-cache-it/angular) which declares TNSImageCacheItModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class TNSImageCacheItModule {
                       ~~~~~~~~~~~~~~~~~~~~~

Webpack compilation complete.
Executing webpack failed with exit code 2.
```

**Comment by eloiqs** [comment]
I have the same issue, did you get around it?

**Comment by atbe** [comment]
@atbe I have not. Ended up switching to native android. Nativescript wasn't delivering the stability I had hoped for so I don't have a use for this package anymore.

**Comment by triniwiz** [comment]
@eloiqs this version supports angular 8 for sure an the new `@triniwiz/nativescript-image-cache-it` supports the newer angular versions 9 not so much oob unless you use the `ngcc` config
