### ISSUE TITLE
NS7 migration

### ISSUE THREAD

**Issue by apsaros** [triniwiz/nativescript-image-cache-it#80]
Hey Triniwiz, thanks for a great plugin and all of your contribution to the NS scene!

Do you plan to migrate this plugin to NS7 anytime soon?
https://nativescript.org/blog/nativescript-7-for-plugin-authors/

Thanks in advance!

**Comment by triniwiz** [comment]
Yes it’s in the final stage but I want to finish the other plugins in the new mono repo

**Comment by apsaros** [comment]
Great news, thanks man, really appreciated! 🥇

**Comment by SmailHammour** [comment]
Any news on this?

**Comment by limux82** [comment]
Any news about the update to ns7?

**Comment by apsaros** [comment]
Hi, not to stress you @triniwiz, but judging from your checklist in your plugins repo, nativescript-image-cache-it seem to be done?:
https://github.com/triniwiz/plugins/issues/1

Is it possible for you to publish this as a branch or is there a public commit we could reference to in order to get the NS7 migrated version of this plugin?

I got some apps in production using nativescript-image-cache-it and it seem to be the last plugin that I'm using that hasn't migrated to NS7. Currently I am (like most of us, I guess) in this weird version-limbo relating to NS, XCode, etc. Due to this, I haven't been able to do any updates to the apps for the past two months or so.

Much appreciated!

**Comment by Whip** [comment]
I'm in the same boat too. Its hard to explain things like these to the clients. At least provide the NS7 version to proplugins subscribers.

**Comment by Whip** [comment]
This is turning out to be a disaster. Haven't been able to release an update to the app for weeks because of this one plugin. 

@triniwiz atleast give us a status and eta

**Comment by SmailHammour** [comment]
> This is turning out to be a disaster. Haven't been able to release an update to the app for weeks because of this one plugin.
> 
> @triniwiz atleast give us a status and eta

@VeeK727 In the meantime you could use this;

[triniwiz-nativescript-image-cache-it-7.0.0.tgz.zip](https://github.com/triniwiz/nativescript-image-cache-it/files/5616040/triniwiz-nativescript-image-cache-it-7.0.0.tgz.zip)

Unzip in the root of the project directory and point to it in your `package.json` file;
```
"@triniwiz/nativescript-image-cache-it": "file:triniwiz-nativescript-image-cache-it-7.0.0.tgz"
```

**Comment by Whip** [comment]
Thanks for the link. Is it prodution ready? Where did you get this?

**Comment by triniwiz** [comment]
@VeeK727 I shared it a while back since I didn't have time to publish the new build also I have 1 more change to make before it's final

**Comment by triniwiz** [comment]
it's now published on npm `@triniwiz/nativescript-image-cache-it`
