### ISSUE TITLE
NS-Vue image flicker when updating ListView

### ISSUE THREAD

**Issue by RayburnTrading** [triniwiz/nativescript-image-cache-it#85]
##Platform:
Android

##Dependencies:

```
"@nativescript/core": "~8.0.0",
"@triniwiz/nativescript-image-cache-it": "^7.0.7",
```

```
  <ImageCacheIt
                class="product-thumbnail"
                horizontalAlignment="left"
                verticalAlignment="top"
                width="100%"
                height="75%"
                errorHolder="~/images/broken.jpg"
                margin="0"
                padding="0"
                :src="`https://www.rayburntrading.com/images/products/${item.pbd_prod_code}t.jpg`"
                @tap="showProductModal(item)"
              />
```

I have a ListView of product thumbnails that load fine but when I update the source array i.e. `this.filteredItemList[index].quantity = 1;` and the ListView updates, all the visible images flicker as if they're being reloaded?

It makes the app feel clunky, can you advise?

Thanks!

**Comment by triniwiz** [comment]
The listview does reload the entire view once updated ( plan to fix that soon ) for now you can use the community collection view or the rad list view

**Comment by RayburnTrading** [comment]
OK, https://github.com/nativescript-community/ui-collectionview seems to work as intended.

RadListView was still reloading each image. Thanks.
